CREATE TABLE M1USER.Customers (
    customer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    address VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    password VARCHAR2(15) NOT NULL
);

-- Optionally, you can add a unique constraint on the email column
ALTER TABLE M1USER.Customers
ADD CONSTRAINT unique_email UNIQUE (email);